SELECT DISTINCT LastName, FirstName, Phone
FROM (CUSTOMER INNER JOIN INVOICE ON 
CUSTOMER.CustomerID=INVOICE.CustomerNumber)
INNER JOIN INVOICE_ITEM ON
INVOICE_ITEM.InvoiceNumber=INVOICE.InvoiceNumber
WHERE INVOICE_ITEM.InvoiceNumber IN
(SELECT InvoiceNumber FROM INVOICE_ITEM
WHERE Item ='Dress Shirt')
ORDER BY LastName ASC, FirstName DESC; 
