SELECT DISTINCT ShipperName, SHIPMENT.ShipmentID, DepartureDate
FROM SHIPMENT 
JOIN SHIPMENT_ITEM ON 
(SHIPMENT.ShipmentID=SHIPMENT_ITEM.ShipmentID)
WHERE SHIPMENT_ITEM.Value>=1000
ORDER BY ShipperName ASC, DepartureDate DESC;