SELECT DISTINCT ShipperName, SHIPMENT.ShipmentID, DepartureDate
FROM ((SHIPMENT 
INNER JOIN SHIPMENT_ITEM
ON SHIPMENT.ShipmentID=SHIPMENT_ITEM.ShipmentID)
INNER JOIN ITEM 
ON SHIPMENT_ITEM.ItemID=ITEM.ItemID)
WHERE ITEM.City='Singapore'
ORDER BY ShipperName, DepartureDate DESC;
