SELECT DISTINCT ShipperName, SHIPMENT.ShipmentID, DepartureDate
FROM (SHIPMENT 
INNER JOIN SHIPMENT_ITEM ON
SHIPMENT.ShipmentID=SHIPMENT_ITEM.ShipmentID)
INNER JOIN ITEM ON
ITEM.ItemID=SHIPMENT_ITEM.ItemID
WHERE ITEM.ItemID IN
(SELECT ItemID FROM ITEM WHERE City ='Singapore')
ORDER BY ShipperName, DepartureDate DESC;
